apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankpack-travel
  labels:
    app: bankpack-travel
spec:
  replicas: 1
  selector:
    matchLabels:
        app: bankpack-travel-svc
  template:
    metadata:
      labels:
        app: bankpack-travel-svc
    spec:
      containers:
      - name: bankpack-travel
        image: drache0311/bankpack-travel:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: bankpack-travel-config
              key: DB_SERVER
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: bankpack-travel-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: bankpack-travel-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: bankpack-travel-config
              key: DB_PASSWORD
        - name: SERVLET_CONTEXT_PATH
          valueFrom:
            configMapKeyRef:
              name: bankpack-travel-config
              key: SERVLET_CONTEXT_PATH
